=== dorivalq/xml-transform/dados/provisionamento-r-mdtrans.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="import">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="version">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:double">
								<xs:attribute name="date" type="xs:date" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="status" type="statusType" minOccurs="0"/>
				<xs:element name="group-list">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="group" type="group1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" use="required" fixed="master-data-transfer"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="metering-point">
		<xs:sequence>
			<xs:element name="identification" type="identificationType" minOccurs="0"/>
			<xs:element name="address" type="addressType" minOccurs="0"/>
			<xs:element name="contact" type="contactType" minOccurs="0"/>
			<xs:element name="communication-list" type="communication-listType" minOccurs="0"/>
			<xs:element name="exchange" minOccurs="0" maxOccurs="2">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="data-list" type="data-list" minOccurs="0"/>
						<xs:element name="group" type="group2"/>
					</xs:sequence>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="meter-mounting"/>
								<xs:enumeration value="meter-dismantling"/>
								<xs:enumeration value="transformer-change"/>
								<xs:enumeration value="contract"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="date" type="xs:dateTime" use="optional"/>
					<xs:attribute name="date-from" type="xs:dateTime" use="optional"/>
					<xs:attribute name="date-to" type="xs:dateTime" use="optional"/>
					<xs:attribute name="name" type="xs:string" use="optional"/>
					<xs:attribute name="description" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="evaluation" type="evaluation" minOccurs="0"/>
			<xs:element name="status" type="statusType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="nr" type="xs:string" use="optional"/>
		<xs:attribute name="state">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="active"/>
					<xs:enumeration value="inactive"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="statusType">
		<xs:attribute name="type" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="ok"/>
					<xs:enumeration value="error"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="addressType">
		<xs:attribute name="country" type="xs:language" use="optional"/>
		<xs:attribute name="zipcode" type="xs:positiveInteger" use="optional"/>
		<xs:attribute name="town" type="xs:string" use="optional"/>
		<xs:attribute name="street" type="xs:string" use="optional"/>
		<xs:attribute name="house" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="identificationType">
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="ident1" type="xs:string" use="optional"/>
		<xs:attribute name="ident2" type="xs:string" use="optional"/>
		<xs:attribute name="ident3" type="xs:string" use="optional"/>
		<xs:attribute name="ident4" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="device">
		<xs:sequence>
			<xs:element name="assignment" type="assignmentType"/>
			<xs:element name="identification" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="identificationType">
							<xs:attribute name="uident1" type="xs:string"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="address" type="addressType" minOccurs="0"/>
			<xs:element name="general" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="password" type="xs:string" use="optional"/>
					<xs:attribute name="address" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="param" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="provider" type="xs:string" use="optional"/>
					<xs:attribute name="voice-nr" type="xs:string" use="optional"/>
					<xs:attribute name="data-nr" type="xs:string" use="optional"/>
					<xs:attribute name="adr2" type="xs:string" use="optional"/>
					<xs:attribute name="user" type="xs:string" use="optional"/>
					<xs:attribute name="pwd2" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="trans-device" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="communication" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="target-prefix" type="xs:string"/>
								<xs:attribute name="target-area-code" type="xs:string"/>
								<xs:attribute name="target-phone-number" type="xs:string"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="datachannel-list">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="datachannel" type="datachannel" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="status" type="statusType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ext-nr" type="xs:string" use="optional"/>
		<xs:attribute name="nr" type="xs:string" use="optional"/>
		<xs:attribute name="state" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="active"/>
					<xs:enumeration value="inactive"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="datachannel">
		<xs:sequence>
			<xs:element name="assignment" type="assignmentType" minOccurs="0"/>
			<xs:element name="identification" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="identificationType">
							<xs:attribute name="uident1" type="xs:string"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="constant" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="transformer-factor-u" type="xs:double"/>
					<xs:attribute name="transformer-factor-i" type="xs:double"/>
					<xs:attribute name="pulse-constant" type="xs:double"/>
					<xs:attribute name="general-constant" type="xs:double"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="meter-device" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="identification" minOccurs="0">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="identificationType">
										<xs:attribute name="uident1" type="xs:string" use="optional"/>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="general" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="password" type="xs:string" use="optional"/>
								<xs:attribute name="address" type="xs:string" use="optional"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="nr" type="xs:string" use="optional"/>
					<xs:attribute name="ext-nr" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="data-list" type="data-list" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="obis-id-code" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="state" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="active"/>
					<xs:enumeration value="inactive"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="obis-new" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="customer">
		<xs:sequence>
			<xs:element name="assignment" type="assignmentType"/>
			<xs:element name="identification" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="identificationType">
							<xs:attribute name="uident1" type="xs:string"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="address" type="addressType" minOccurs="0"/>
			<xs:element name="contact" type="contactType" minOccurs="0"/>
			<xs:element name="communication-list" type="communication-listType" minOccurs="0"/>
			<xs:element name="evaluation" type="evaluation" minOccurs="0"/>
			<xs:element name="status" type="statusType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="nr" type="xs:string" use="optional"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="state" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="active"/>
					<xs:enumeration value="inactive"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="assignmentType">
		<xs:attribute name="ident1" type="xs:string" use="optional"/>
		<xs:attribute name="ident2" type="xs:string" use="optional"/>
		<xs:attribute name="ident3" type="xs:string" use="optional"/>
		<xs:attribute name="ident4" type="xs:string" use="optional"/>
		<xs:attribute name="ident5" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="contactType">
		<xs:attribute name="last-name" type="xs:string" use="optional"/>
		<xs:attribute name="first-name" type="xs:string" use="optional"/>
		<xs:attribute name="person" type="xs:string" use="optional"/>
		<xs:attribute name="business" type="xs:string" use="optional"/>
		<xs:attribute name="address-form" type="xs:string" use="optional"/>
		<xs:attribute name="title" type="xs:string" use="optional"/>
		<xs:attribute name="search" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="communication-listType">
		<xs:sequence>
			<xs:element name="communication" maxOccurs="6">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="type" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="phone"/>
										<xs:enumeration value="email"/>
										<xs:enumeration value="fax"/>
										<xs:enumeration value="modem"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="nr" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:unsignedShort">
										<xs:enumeration value="1"/>
										<xs:enumeration value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="group1">
		<xs:sequence>
			<xs:element name="assignment" type="assignmentType" minOccurs="0"/>
			<xs:element name="identification" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="identificationType">
							<xs:attribute name="uident1" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="group" type="group1" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="metering-point-list" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="metering-point" type="metering-point" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="device-list" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="device" type="device" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="customer-list" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="customer" type="customer" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="customer"/>
					<xs:enumeration value="device"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="group2">
		<xs:sequence>
			<xs:element name="assignment" type="assignmentType" minOccurs="0"/>
			<xs:element name="identification" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="identificationType">
							<xs:attribute name="uident1" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="group" type="group2" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="device" type="device" minOccurs="0"/>
			<xs:element name="customer" type="customer" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="customer"/>
					<xs:enumeration value="device"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="data-list">
		<xs:sequence>
			<xs:element name="data" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="evaluation">
		<xs:sequence>
			<xs:element name="assignment" type="assignmentType"/>
			<xs:element name="general" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="description" type="xs:string" use="optional"/>
					<xs:attribute name="calc-till-now" type="xs:boolean" use="optional"/>
					<xs:attribute name="plus-n-day" type="xs:positiveInteger" use="optional"/>
					<xs:attribute name="oppress-state" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="result-datachannel" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="identification" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="uident1" type="xs:string" use="optional"/>
								<xs:attribute name="ident1" type="xs:string" use="optional"/>
								<xs:attribute name="ident2" type="xs:string" use="optional"/>
								<xs:attribute name="ident3" type="xs:string" use="optional"/>
								<xs:attribute name="ident4" type="xs:string" use="optional"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="general" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="integration-period" type="xs:positiveInteger" use="optional"/>
								<xs:attribute name="unit" type="xs:string" use="optional"/>
								<xs:attribute name="timezone" type="xs:string" use="optional"/>
								<xs:attribute name="daychange" type="xs:string" use="optional"/>
								<xs:attribute name="balancing" use="optional">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="d"/>
											<xs:enumeration value="dm"/>
											<xs:enumeration value="dmy"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="obis-id-code" type="xs:string" use="optional"/>
					<xs:attribute name="measuring" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="primary"/>
								<xs:enumeration value="secondary"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="source-datachannel-list" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="source-datachannel" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="assignment">
										<xs:complexType>
											<xs:complexContent>
												<xs:extension base="assignmentType">
													<xs:attribute name="search" use="optional">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="all"/>
																<xs:enumeration value="customer"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
												</xs:extension>
											</xs:complexContent>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="type" use="optional">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="datachannel"/>
											<xs:enumeration value="datachannel-link"/>
											<xs:enumeration value="load-profile-calculation"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="formula-nr" type="xs:positiveInteger" use="optional"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="time-frame-list" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="time-frame" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="date-from" type="xs:dateTime" use="optional"/>
								<xs:attribute name="date-to" type="xs:dateTime" use="optional"/>
								<xs:attribute name="name" type="xs:string" use="optional"/>
								<xs:attribute name="person" type="xs:string" use="optional"/>
								<xs:attribute name="editor" type="xs:string" use="optional"/>
								<xs:attribute name="formula" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="load-profile-calculation"/>
					<xs:enumeration value="datachannel-link"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== dorivalq/xml-transform/dados/provisionamento-r-mdtrans.xml
<?xml version="1.0" encoding="UTF-8"?>
<import name="master-data-transfer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="provisionamento-r-mdtrans.xsd">
  <version date="2001-01-01">0.0</version>
  <status type="ok"/>
  <group-list>
    <group name="" type="customer">
      <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
      <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
      <group name="" type="customer"/>
      <metering-point-list>
        <metering-point name="" nr="" state="active">
          <identification description="" ident1="" ident2="" ident3="" ident4=""/>
          <address country="EN" house="" street="" town="" zipcode="1"/>
          <contact address-form="" business="" first-name="" last-name="" person="" search="" title=""/>
          <communication-list>
            <communication nr="1" type="phone">communication</communication>
          </communication-list>
          <exchange date="2001-12-31T12:00:00" date-from="2001-12-31T12:00:00" date-to="2001-12-31T12:00:00" description="" name="" type="meter-mounting">
            <data-list>
              <data name="">data</data>
            </data-list>
            <group name="" type="customer">
              <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
              <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
              <group name="" type="customer"/>
              <device ext-nr="" nr="" state="active">
                <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
                <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
                <address country="EN" house="" street="" town="" zipcode="1"/>
                <general address="" password=""/>
                <param adr2="" data-nr="" provider="" pwd2="" user="" voice-nr=""/>
                <trans-device/>
                <datachannel-list>
                  <datachannel obis-id-code="123" obis-new="" state="active"/>
                </datachannel-list>
                <status type="ok"/>
              </device>
              <customer nr="" state="active" type="">
                <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
                <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
                <address country="EN" house="" street="" town="" zipcode="1"/>
                <contact address-form="" business="" first-name="" last-name="" person="" search="" title=""/>
                <communication-list>
                  <communication nr="1" type="phone">communication</communication>
                </communication-list>
                <evaluation name="" type="load-profile-calculation">
                  <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
                </evaluation>
                <status type="ok"/>
              </customer>
            </group>
          </exchange>
          <evaluation name="" type="load-profile-calculation">
            <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
            <general calc-till-now="true" description="" oppress-state="" plus-n-day="1"/>
            <result-datachannel measuring="primary" obis-id-code="">
              <identification ident1="" ident2="" ident3="" ident4="" uident1=""/>
              <general balancing="d" daychange="" integration-period="1" timezone="" unit=""/>
            </result-datachannel>
            <source-datachannel-list>
              <source-datachannel formula-nr="1" type="datachannel">
                <assignment ident1="" ident2="" ident3="" ident4="" ident5="" search="all"/>
              </source-datachannel>
            </source-datachannel-list>
            <time-frame-list>
              <time-frame date-from="2001-12-31T12:00:00" date-to="2001-12-31T12:00:00" editor="" formula="" name="" person=""/>
            </time-frame-list>
          </evaluation>
          <status type="ok"/>
        </metering-point>
      </metering-point-list>
      <device-list>
        <device ext-nr="" nr="" state="active">
          <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
          <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
          <address country="EN" house="" street="" town="" zipcode="1"/>
          <general address="" password=""/>
          <param adr2="" data-nr="" provider="" pwd2="" user="" voice-nr=""/>
          <trans-device>
            <communication target-area-code="" target-phone-number="" target-prefix=""/>
          </trans-device>
          <datachannel-list>
            <datachannel obis-id-code="123" obis-new="" state="active">
              <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
              <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
              <constant general-constant="0.0" pulse-constant="0.0" transformer-factor-i="0.0" transformer-factor-u="0.0"/>
              <meter-device ext-nr="" nr="">
                <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
                <general address="" password=""/>
              </meter-device>
              <data-list>
                <data name="">data</data>
              </data-list>
            </datachannel>
          </datachannel-list>
          <status type="ok"/>
        </device>
      </device-list>
      <customer-list>
        <customer nr="" state="active" type="">
          <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
          <identification description="" ident1="" ident2="" ident3="" ident4="" uident1=""/>
          <address country="EN" house="" street="" town="" zipcode="1"/>
          <contact address-form="" business="" first-name="" last-name="" person="" search="" title=""/>
          <communication-list>
            <communication nr="1" type="phone">communication</communication>
          </communication-list>
          <evaluation name="" type="load-profile-calculation">
            <assignment ident1="" ident2="" ident3="" ident4="" ident5=""/>
            <general calc-till-now="true" description="" oppress-state="" plus-n-day="1"/>
            <result-datachannel measuring="primary" obis-id-code="">
              <identification ident1="" ident2="" ident3="" ident4="" uident1=""/>
              <general balancing="d" daychange="" integration-period="1" timezone="" unit=""/>
            </result-datachannel>
            <source-datachannel-list>
              <source-datachannel formula-nr="1" type="datachannel">
                <assignment ident1="" ident2="" ident3="" ident4="" ident5="" search="all"/>
              </source-datachannel>
            </source-datachannel-list>
            <time-frame-list>
              <time-frame date-from="2001-12-31T12:00:00" date-to="2001-12-31T12:00:00" editor="" formula="" name="" person=""/>
            </time-frame-list>
          </evaluation>
          <status type="ok"/>
        </customer>
      </customer-list>
    </group>
  </group-list>
</import>
