=== dorivalq/xml-transform/dados/provisionamento-r-UniversalAMIInterface.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema targetNamespace="http://www.emeter.com/energyip/amiinterface" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:tns="http://www.emeter.com/energyip/amiinterface" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="UniversalAMIInterfaceTypes.xsd"/>
	<xs:complexType name="MessageHeader">
		<xs:annotation>
			<xs:documentation>Message header containing descriptive information
				about the message.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:annotation>
				<xs:documentation><![CDATA[General information regarding the message payload.
					These fields are used to provide application context. The fields
					are not intended to be a complete list of properties used by
					middleware for message management.]]></xs:documentation>
			</xs:annotation>
			<xs:element name="verb" minOccurs="0">
				<xs:annotation>
					<xs:documentation><![CDATA[This enumerated list of verbs that can be used to
						form message types in compliance with the IEC 61968 standard.
						get - Meter Data Request
						reply - Meter Data Response
						create - Send Meter Data
						created - Optional confirmation of receipt of Meter Data
					]]></xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="cancel"/>
						<xs:enumeration value="canceled"/>
						<xs:enumeration value="change"/>
						<xs:enumeration value="changed"/>
						<xs:enumeration value="create"/>
						<xs:enumeration value="created"/>
						<xs:enumeration value="close"/>
						<xs:enumeration value="closed"/>
						<xs:enumeration value="delete"/>
						<xs:enumeration value="deleted"/>
						<xs:enumeration value="get"/>
						<xs:enumeration value="show"/>
						<xs:enumeration value="request"/>
						<xs:enumeration value="reply"/>
						<xs:enumeration value="ack"/>
						<xs:enumeration value="subscribe"/>
						<xs:enumeration value="unsubscribe"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="noun" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation><![CDATA[The Noun of the Control Area identifies the main
						subject of the message type, typically a real world object defined
						in the CIM.
						Intended usage - MeterData
					]]></xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="revision" type="xs:string" default="1" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Revision level of the message type.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="dateTime" type="xs:dateTime" minOccurs="0">
				<xs:annotation>
					<xs:documentation><![CDATA[Application level relevant time and date for when
						this instance of the message type was produced. This is not
						intended to be used by middleware for message management.
					]]></xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="source" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Source system. May be used for invocation context
						authorization</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="messageID" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Unique message ID to be used for correlating
						replies and tracking messages</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="asyncReplyTo" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>If reply is expected to be async then the
						proptocol specific address where reply needs to be sent
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReplyHeader">
		<xs:sequence>
			<xs:element name="replyCode" type="xs:string"/>
			<xs:element name="replyText" type="xs:string" minOccurs="0"/>
			<xs:element name="correlationId" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>messageId of the Request message.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MeterAddRequestPayload">
		<xs:complexContent>
			<xs:extension base="tns:MeterChangeRequestPayload"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MeterUpdateRequestPayload">
		<xs:complexContent>
			<xs:extension base="tns:MeterChangeRequestPayload"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MeterDeleteRequestPayload">
		<xs:complexContent>
			<xs:extension base="tns:MeterChangeRequestPayload"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MeterChangeRequestPayload">
		<xs:sequence>
			<xs:element name="meterAsset" type="tns:MeterAsset"/>
			<xs:element name="comFunction" type="tns:ComFunction"/>
			<xs:element name="serviceDeliveryPoint" type="tns:ServiceDeliveryPoint"/>
			<xs:element name="serviceLocation" type="tns:ServiceLocation"/>
			<xs:element name="customerAccount" type="tns:CustomerAccount"/>
			<xs:element name="provisioningGroup" type="tns:ProvisioningGroup" minOccurs="0"/>
			<xs:element name="collectionGroup" type="tns:CollectionGroup" minOccurs="0"/>
			<xs:element name="broadcastGroup" type="tns:BroadcastGroup" minOccurs="0"/>
			<xs:element name="executeStartTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="executeExpireTime" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PingRequest">
		<xs:sequence>
			<xs:element name="meterAsset" type="tns:MeterAsset"/>
			<xs:element name="executeStartTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="executeExpireTime" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="JobCancelRequest">
		<xs:sequence>
			<xs:element name="correlationId" type="xs:string"/>
			<xs:element name="executeStartTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="executeExpireTime" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MeterConnectRequestPayload">
		<xs:sequence>
			<xs:element name="meterAsset" type="tns:MeterAsset"/>
			<xs:element name="executeStartTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="executeExpireTime" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MeterDisconnectRequestPayload">
		<xs:sequence>
			<xs:element name="meterAsset" type="tns:MeterAsset"/>
			<xs:element name="executeStartTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="executeExpireTime" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MeterConnectArmedRequestPayload">
		<xs:sequence>
			<xs:element name="meterAsset" type="tns:MeterAsset"/>
			<xs:element name="executeStartTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="executeExpireTime" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="RequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="MeterDataRequest">
		<xs:sequence>
			<xs:element name="startTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="endTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="versionTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="Meter" type="tns:MeterAsset"/>
			<xs:element name="measurementProfile" type="xs:string" minOccurs="0"/>
			<xs:element name="readingTypeList" type="tns:ReadingTypeList" minOccurs="0"/>
			<xs:element name="eventCategory" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="retrieveRegisterReads" type="xs:boolean" minOccurs="0"/>
			<xs:element name="retrieveIntervalReads" type="xs:boolean" minOccurs="0"/>
			<xs:element name="demandReset" type="xs:boolean" minOccurs="0"/>
			<xs:element name="retrieveEvents" type="xs:boolean" minOccurs="0"/>
			<xs:element name="executeStartTime" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="executeExpireTime" type="xs:dateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ProvisioningGroup">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="fuseSize" type="xs:double"/>
			<xs:element name="readingType" type="tns:ReadingType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CollectionGroup">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="readfrequency" type="xs:string"/>
			<xs:element name="readwindowstarttime" type="xs:time"/>
			<xs:element name="readwindowendtime" type="xs:time"/>
			<xs:element name="deliveryfrequency" type="xs:string"/>
			<xs:element name="deliverywindowstarttime" type="xs:time"/>
			<xs:element name="deliverywindowendtime" type="xs:time"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BroadcastGroup">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="MeterAssetAddRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:MeterAddRequestPayload" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetAddReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetUpdateRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:MeterUpdateRequestPayload" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetUpdateReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
				<xs:element name="meterReads" type="tns:MeterReadings" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetDeleteRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:MeterDeleteRequestPayload" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetDeleteReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetConnectRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:MeterConnectRequestPayload" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetConnectReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
				<xs:element name="meterReads" type="tns:MeterReadings" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetDisconnectRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:MeterDisconnectRequestPayload" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetDisconnectReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
				<xs:element name="meterReads" type="tns:MeterReadings" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetConnectArmedRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:MeterConnectArmedRequestPayload" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetConnectArmedReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
				<xs:element name="meterReads" type="tns:MeterReadings" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetPingRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:PingRequest" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterAssetPingReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="JobCancelRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:JobCancelRequest" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="JobCancelReplyMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterReadsRequestMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header" type="tns:MessageHeader"/>
				<xs:element name="payload" type="tns:MeterDataRequest" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MeterReadsReplyMessage" type="tns:MeterReadsReply"/>
	<xs:element name="MeterDataMessage" type="tns:MeterReadsMessageType"/>
	<xs:complexType name="MeterReadsReply">
		<xs:complexContent>
			<xs:extension base="tns:MeterReadsMessageType">
				<xs:sequence>
					<xs:element name="reply" type="tns:ReplyHeader" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MeterReadsMessageType">
		<xs:sequence>
			<xs:element name="header" type="tns:MessageHeader"/>
			<xs:element name="payload" type="tns:MeterReadings" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== dorivalq/xml-transform/dados/provisionamento-r-UniversalAMIInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:MeterAssetUpdateReplyMessage xmlns:tns="http://www.emeter.com/energyip/amiinterface" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.emeter.com/energyip/amiinterface provisionamento-r-UniversalAMIInterface.xsd ">
  <tns:header>
    <tns:verb>cancel</tns:verb>
    <tns:noun>tns:noun</tns:noun>
    <tns:revision>1</tns:revision>
    <tns:dateTime>2001-12-31T12:00:00</tns:dateTime>
    <tns:source>tns:source</tns:source>
    <tns:messageID>tns:messageID</tns:messageID>
    <tns:asyncReplyTo>tns:asyncReplyTo</tns:asyncReplyTo>
  </tns:header>
  <tns:reply>
    <tns:replyCode>tns:replyCode</tns:replyCode>
    <tns:replyText>tns:replyText</tns:replyText>
    <tns:correlationId>tns:correlationId</tns:correlationId>
  </tns:reply>
  <tns:meterReads>tns:meterReads</tns:meterReads>
</tns:MeterAssetUpdateReplyMessage>
