=== dorivalq/xml-transform/dados/retorno-entrada-ord.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="result">
		<xs:annotation>
			<xs:documentation>Includes measuring data result</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="version">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:double">
								<xs:attribute name="date" type="xs:date" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="request-id" type="xs:string"/>
				<xs:element name="state">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="succeeded"/>
							<xs:enumeration value="failed"/>
							<xs:enumeration value="nodata"/>
							<xs:enumeration value="partialdata"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="payload">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="identification" type="identification" minOccurs="0"/>
							<xs:element name="data" type="data" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="identification">
		<xs:annotation>
			<xs:documentation>Includes identification data of a specific datachannel</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="metering-point" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="id" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:maxLength value="33"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="device" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="nr" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="datachannel">
				<xs:complexType>
					<xs:attribute name="obis-id-code" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
            <xs:element name="device-list" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                    <xs:element name="device" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="nr" type="xs:string"/>
                    <xs:attribute name="date-from" type="xs:dateTime"/>
                    <xs:attribute name="date-to" type="xs:dateTime"/>
                </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="data">
		<xs:annotation>
			<xs:documentation>Includes measuring data</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="time-frame">
				<xs:complexType>
					<xs:attribute name="date-from" type="xs:string" use="required"/>
					<xs:attribute name="date-to" type="xs:string" use="required"/>
					<xs:attribute name="ref-date-from" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="data-type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="lp"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="integration-period" type="xs:unsignedInt"/>
            <xs:element name="unit" type="xs:string"/>
			<xs:element name="plausibility">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="succeeded"/>
						<xs:enumeration value="failed"/>
						<xs:enumeration value="notset"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="value-list">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="val" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:double">
										<xs:attribute name="dt" type="xs:string" use="required"/>
										<xs:attribute name="st" type="xs:string" use="required"/>
										<xs:attribute name="t1" type="xs:string" use="required"/>
										<xs:attribute name="t2" type="xs:string" use="required"/>
										<xs:attribute name="lb" type="xs:string" use="optional"/>
										<xs:attribute name="unit" type="xs:string" use="optional"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== dorivalq/xml-transform/dados/retorno-entrada-ord.xml
<?xml version="1.0" encoding="UTF-8"?>
<result xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="retorno-entrada-ord.xsd">
  <version date="2001-01-01">0.0</version>
  <request-id>request-id</request-id>
  <state>succeeded</state>
  <payload>
    <identification>
      <metering-point id=""/>
      <device nr=""/>
      <datachannel obis-id-code=""/>
      <device-list>
        <device date-from="2001-12-31T12:00:00" date-to="2001-12-31T12:00:00" nr=""/>
      </device-list>
    </identification>
    <data>
      <time-frame date-from="" date-to="" ref-date-from=""/>
      <data-type>lp</data-type>
      <integration-period>0</integration-period>
      <unit>unit</unit>
      <plausibility>succeeded</plausibility>
      <value-list>
        <val dt="" lb="" st="" t1="" t2="" unit="">0.0</val>
      </value-list>
    </data>
  </payload>
</result>
